# Generated by Django 4.2.2 on 2023-06-20 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
