databases:
  - name: neverhot
    databaseName: neverhot
    user: neverhot

services:
  - type: web
    name: neverhot
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn neverhot.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: neverhot
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4