# Generated by Django 4.2.2 on 2023-08-21 12:04

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_name", models.CharField(max_length=500)),
                ("country", models.CharField(blank=True, max_length=500)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("icon", models.CharField(blank=True, max_length=500)),
                ("img_path", models.CharField(default="default.jpg", max_length=200)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("added", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="city_name", unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp", models.FloatField(blank=True)),
                ("temp_feel", models.FloatField(blank=True)),
                ("hum", models.IntegerField(blank=True)),
                ("wind_speed", models.FloatField(blank=True)),
                ("datetime", models.DateTimeField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=500)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("dt_naive", models.BooleanField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("city_name", "lat", "lon"), name="unique location"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forecast",
            unique_together={("city", "datetime")},
        ),
    ]
