# Generated by Django 4.2.2 on 2023-07-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("temp", models.FloatField(blank=True, null=True)),
                ("temp_feel", models.FloatField(blank=True, null=True)),
                ("hum", models.IntegerField(blank=True, null=True)),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="weather.city"
                    ),
                ),
            ],
        ),
    ]
