# Generated by Django 4.2.4 on 2023-08-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city_name",
            field=models.CharField(max_length=500, verbose_name="city_name"),
        ),
    ]
