# Generated by Django 4.2.2 on 2023-07-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0002_weather"),
    ]

    operations = [
        migrations.AddField(
            model_name="weather",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="datetime",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="hum",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="temp",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="temp_feel",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="weather",
            name="wind_speed",
            field=models.FloatField(null=True),
        ),
    ]
