# Generated by Django 4.2.2 on 2023-07-21 12:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0003_city_icon"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="forecast",
            unique_together={("city", "datetime")},
        ),
    ]
