# Generated by Django 4.2.2 on 2023-07-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0004_alter_forecast_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="dt_naive",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
