# Generated by Django 4.2.2 on 2023-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0005_forecast_dt_naive"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="img_path",
            field=models.CharField(default="default.jpg", max_length=200),
        ),
    ]
