# Generated by Django 4.2.2 on 2023-08-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0006_city_img_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="city_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("city_name", "country", "lat", "lon")},
        ),
    ]
