# Generated by Django 4.2.2 on 2023-08-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0007_alter_city_city_name_alter_city_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="city",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("lat", "lon"), name="unique location"
            ),
        ),
    ]
