# Generated by Django 4.2.2 on 2023-08-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0009_remove_city_unique_location"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("lat", "lon"), name="unique location"
            ),
        ),
    ]
