# Generated by Django 4.2.2 on 2023-08-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("weather", "0010_city_unique_location"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="city",
            name="unique location",
        ),
        migrations.AddConstraint(
            model_name="city",
            constraint=models.UniqueConstraint(
                fields=("city_name", "lat", "lon"), name="unique location"
            ),
        ),
    ]
